#!/usr/bin/env node
const connect = require('connect');

const ballotStyles = require('./data/ballotStyles');
const castVoteRecords = require('./data/castVoteRecords');
const contests = require('./data/contests');
const counties = require('./data/counties');
const countyDashboard = require('./data/countyDashboard');
const dosDashboard = require('./data/dosDashboard');


const app = connect();

const route = (m, path, handler) => {
    const headers = contentType => ({
        'access-control-allow-origin': '*',
        'content-type': contentType,
    });

    app.use(path, (req, res, done) => {
        if (req.method.toLowerCase() !== m.toLowerCase()) {
            res.writeHead(405, headers);
            res.end();
            return done();
        }

        const { data, status } = handler(req, res);

        res.writeHead(status, headers('application/json'));

        if (typeof data === 'string') {
            res.end(JSON.stringify({ result: data }));
        } else {
            res.end(JSON.stringify(data));
        }

        done();
    });
};

const res = status => data => (req, res) => ({ status, data });

const ok = res(200);
const badRequest = res(400);
const unauthorized = res(401);
const notFound = res(404);
const serverError = res(500);

route('get', '/ballot-style', ok(ballotStyles));
route('get', '/cvr', ok(castVoteRecords));
route('get', '/contest', ok(contests));
route('post', '/auth-state-admin', ok('Authenticated'));
route('get', '/dos-dashboard', ok(dosDashboard));
route('post', '/risk-limit-comp-audits', ok(''));
route('post', '/select-contests', ok(''));
route('post', '/upload-random-seed', ok(''));
route('get', '/county-dashboard', ok(countyDashboard));
route('post', '/auth-county-admin', ok('Authenticated'));


app.listen(4000);
