insert into administrator (id, username, full_name, last_login_time, last_logout_time, county_id, type, version) values 
(-9, 'freefair01', 'Free & Fair Test State Administrator', null, null, null, 'STATE', 0);
insert into administrator (id, username, full_name, last_login_time, last_logout_time, county_id, type, version) values 
(-165, 'freefair02', 'Free & Fair Test County Administrator', null, null, 64, 'COUNTY', 0);
