type CountyASMState
    = 'COUNTY_INITIAL_STATE'
    | 'COUNTY_AUTHENTICATED'
    | 'AUDIT_BOARD_OK'
    | 'BALLOT_MANIFEST_OK'
    | 'CVRS_OK'
    | 'AUDIT_BOARD_AND_BALLOT_MANIFEST_OK'
    | 'AUDIT_BOARD_AND_CVRS_OK'
    | 'BALLOT_MANIFEST_AND_CVRS_OK'
    | 'AUDIT_BOARD_BALLOT_MANIFEST_AND_CVRS_OK'
    | 'COUNTY_AUDIT_UNDERWAY'
    | 'COUNTY_AUDIT_COMPLETE'
    | 'DEADLINE_MISSED';


type AuditBoardASMState
    = 'AUDIT_INITIAL_STATE'
    | 'AUDIT_IN_PROGRESS'
    | 'AUDIT_REPORT_SUBMITTED';
