#!/bin/bash

# Build a ColoradoRLA release zip file

set -eux -o pipefail

export TRAVIS_BUILD_DIR=`git rev-parse --show-toplevel`
export CLIENT_DIR="${TRAVIS_BUILD_DIR}/client"
export SERVER_DIR="${TRAVIS_BUILD_DIR}/server/eclipse-project"
export TEST_DIR="${TRAVIS_BUILD_DIR}/test"

version=$(sed < "${SERVER_DIR}/pom.xml" '2 s/xmlns=".*"//g' | xmllint --xpath '/project/version/text()' - 2>/dev/null)
relname=colorado-rla-release-$version
reldir=$SERVER_DIR/target/$relname


# setup
cd $SERVER_DIR
mvn clean
mkdir -p target
mkdir -p $reldir

# server
cd $SERVER_DIR
mvn package > target/mvn.stdout
jar=target/colorado_rla-$version-shaded.jar
cp $jar $reldir/corla-server.jar

# httpd
cp ../deploy/corla.conf $reldir


# client
cd $CLIENT_DIR
npm install --no-audit
./script/dist
cd dist
zip -r $reldir/corla-client.zip *

cp $TEST_DIR/corla-test-credentials.psql $reldir

relzip=$SERVER_DIR/target/$relname.zip

cd $SERVER_DIR/target
zip -r $relzip $relname
