#!/usr/bin/env bash
set -eux -o pipefail
readonly __dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

readonly cmd='PGPASSWORD=corla psql -U corla -h localhost -d corla'

sudo -u postgres ${cmd}
