Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.network "forwarded_port",
    guest: 80,
    host: 8080

  config.vm.network "forwarded_port",
    guest: 443,
    host: 8443

  config.vm.network "forwarded_port",
    guest: 8888,
    host: 8888

  config.vm.provision "shell",
    path: "provision.sh"

  config.vm.synced_folder "../", "/vagrant",
    type: "rsync",
    rsync__exclude: ".git/"
end
