/*
 * Free & Fair Colorado RLA System
 * 
 * @title ColoradoRLA
 * @created Jul 25, 2017
 * @copyright 2017 Colorado Department of State
 * @license SPDX-License-Identifier: AGPL-3.0-or-later
 * @creator Joey Dodds <jdodds@galois.com>
 * @description A system to assist in conducting statewide risk-limiting audits.
 */

package us.freeandfair.corla.csv;

import java.util.OptionalInt;

/**
 * A common interface to parsers for CVR info in various formats.
 * 
 * @author Daniel M. Zimmerman <dmz@freeandfair.us>
 * @version 1.0.0
 */
public interface CVRExportParser {
  /**
   * Parse the CVRs. The export data and other supplementary information is provided
   * to the CVR parser in some way outside this interface (such as a constructor 
   * call).
   * 
   * @return true if the parse was successful, false otherwise.
   */
  boolean parse();
  
  /**
   * The number of records parsed from the CVR file. 
   * 
   * @return the number of records; empty if parsing has not yet occurred.
   */
  OptionalInt recordCount();
  
  /**
   * The error message, if any, generated by the parser.
   * 
   * @return the error message, or null if there was no error.
   */
  String errorMessage();
}
