#!/usr/bin/env bash
set -eu -o pipefail

ls_changed_files() {
  git diff --name-only master
}

any_changed_file_in_dir() {
  readonly changed_files=$(ls_changed_files)

  readonly dir=$1

  for f in ${changed_files}; do
    if [[ ${f} == ${dir}* ]]; then
      echo "\`${f}' in dir \`${dir}' changed"
      exit 0
    fi
  done

  exit 1
}

if ! (( $# )); then
  echo "Usage: \`$(basename $0) DIR_PREFIX\`"
  exit 1
fi

any_changed_file_in_dir $1
